name: Release

on:
  push:
    branches:
      - build-matrix


jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Check if version changed
        id: version_check
        run: |
          git diff HEAD~1 HEAD -U0 | grep -E "^+version ="

  test:
    runs-on: ubuntu-latest
    needs: version
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    needs: test
    steps:
    - uses: actions/checkout@v1
    - uses: hecrj/setup-rust-action@master
      with:
        rust-version: stable
    - name: Set up Python 3.5
      uses: actions/setup-python@v1
      with:
        python-version: 3.5
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install pyo3-pack
      run: |
        pip install pyo3-pack
    - name: Publish package
      run: |
        pyo3-pack publish -i python3.5 -i python3.6 -i python3.7
