name: Release

on:
  push:
    branches:
      - master
    paths:
      - '_version'

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Verify version matches
      run: head -3 Cargo.toml | tail -1 | grep $(cat _version)
  rust:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
  python:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        version: '3.7'
        architecture: 'x64'
    - name: Setup env
      run: make venv
    - name: Run tests
      run: make python_tests

  build-ubuntu:
    runs-on: ubuntu-latest
    needs: [version, rust, python]
    steps:
    - uses: actions/checkout@v1
    - uses: hecrj/setup-rust-action@master
      with:
        rust-version: stable
    - name: Set up Python 3.5
      uses: actions/setup-python@v1
      with:
        python-version: 3.5
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install maturin
      run: |
        pip install maturin
    - name: Publish package
      env:
        PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
        PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        maturin publish \
          -u $PYPI_USERNAME \
          -p $PYPI_PASSWORD \
          -i python3.5 \
          -i python3.6 \
          -i python3.7
    - name: Install hub
      run: |
        wget https://github.com/github/hub/releases/download/v2.12.3/hub-linux-amd64-2.12.3.tgz -O hub.tgz
        tar -xvf hub.tgz
        mv hub-linux-amd64-2.12.3/bin/hub .
    - name: Tag release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_USER: ikornaselur
      run: |
        VERSION="v$(cat _version)"
        ./hub release show $VERSION || ./hub release create -m "$VERSION" $VERSION
        for a in target/wheels/*.whl; do ./hub release edit -a $a -m "$VERSION" $VERSION; done
  build-macos:
    runs-on: macos-latest
    needs: test
    steps:
    - uses: actions/checkout@v1
    - uses: hecrj/setup-rust-action@master
      with:
        rust-version: stable
    - name: Set up Python 3.5
      uses: actions/setup-python@v1
      with:
        python-version: 3.5
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install maturin
      run: |
        pip install maturin
    - name: Publish package
      env:
        PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
        PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        maturin publish \
          -u $PYPI_USERNAME \
          -p $PYPI_PASSWORD \
          -i python3.5 \
          -i python3.6 \
          -i python3.7
    - name: Install hub
      run: |
        wget https://github.com/github/hub/releases/download/v2.12.3/hub-darwin-amd64-2.12.3.tgz -O hub.tgz
        tar -xvf hub.tgz
        mv hub-darwin-amd64-2.12.3/bin/hub .
    - name: Tag release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_USER: ikornaselur
      run: |
        VERSION="v$(cat _version)"
        ./hub release show $VERSION || ./hub release create -m "$VERSION" $VERSION
        for a in target/wheels/*.whl; do ./hub release edit -a $a -m "$VERSION" $VERSION; done
