name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Verify version matches
      run: head -3 Cargo.toml | tail -1 | grep $(cat _version)
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
